<?php
$this->title = 'Videoclub ZF';
$this->headTitle($this->title);
?>
<p>Êtes-vous sûr de vouloir désactiver le compte pour
    ' <?php echo $this->escape($this->personne->prenom); ?>
	<?php echo $this->escape($this->personne->nom); ?> ' ?
</p>
<form action="<?php echo $this->url(array('action'=>'desactiver')); ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $this->personne->id; ?>" />
    <input type="submit" name="desactiver" value="Oui" />
    <input type="button" name="annuler" value="Non" />
</div>
</form>
