<?php
// $this->title = 'Les clients';
// $this->headTitle($this->title);
?>

<table>
    <tr>
        <th>Numéro d'adhérent</th>
        <th>Nom</th>
        <th>Prénom</th>
		<th></th>
    </tr>
    <tr>
        <td><?php echo $this->escape($personne->numeroAdherent); ?></td>
        <td><?php echo $this->escape($personne->nom); ?></td>
		<td><?php echo $this->escape($personne->prenom); ?></td>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'personne',
                'action'=>'modifier', 'id'=>$employe->id));?>">Modifier</a>
             &nbsp|&nbsp
            <a href="<?php echo $this->url(array('controller'=>'personne',
                'action'=>'desactive', 'id'=>$employe->id));?>">Désactiver</a>
        </td>

    </tr>
</table>
