<?php
$this->title = 'Les Acteurs Réalisateurs';
$this->headTitle($this->title);
?>
<p>Tous ce qui concerne les personnes (clients ou employés).</p>
<P>Vous pouvez afficher toutes les personnes.<br />
<a href="<?php echo $this->url(array('controller'=>'Personne',
        'action'=>'liste'));?>">Afficher la liste</a></p>
<p>Vous pouvez ajouter une personne.<br />
<a href="<?php echo $this->url(array('controller'=>'Personne',
        'action'=>'ajouter'));?>">Ajouter</a></p>
<p>Vous pouvez rechercher une personne.<br />
<a href="<?php echo $this->url(array('controller'=>'Personne',
        'action'=>'rechercher'));?>">Rechercher</a></p>
