<?php
// $this->title = 'Les clients';
// $this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'personne',
        'action'=>'ajouter'));?>">Ajouter un employé</a></p>
<table>
    <tr>
        <th>Numéro d'adhérent</th>
        <th>Nom</th>
        <th>Prénom</th>
		<th></th>
    </tr>
<?php foreach($this->paginator as $employe) : ?> <!-- je met $this->personne car dans le controller j'ai utilisé $this->view->personne -->
    <tr>
        <td><?php echo $this->escape($employe->numeroAdherent); ?></td>
        <td><?php echo $this->escape($employe->nom); ?></td>
		<td><?php echo $this->escape($employe->prenom); ?></td>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'personne',
                'action'=>'modifier', 'id'=>$employe->id));?>">Modifier</a>
            &nbsp|&nbsp
            <a href="<?php echo $this->url(array('controller'=>'personne',
                'action'=>'detail', 'id'=>$employe->id));?>">Détails</a>
        </td>

    </tr>
<?php endforeach; ?>
</table>
<?php echo $this->paginator; ?>
