<?php
$this->title = 'Videoclub ZF';
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'personne',
        'action'=>'ajouter'));?>">Ajouter un client</a></p>
<div class="row">
    <div class="col-sm-12 col-md-offset-4 col-md-8">
        <table>
            <tr>
                <th>Numéro d'adhérent</th>
                <th>Nom</th>
                <th>Prénom</th>
        		<th></th>
            </tr>
        <?php foreach($this->paginator as $client) : ?> <!-- je met $this->personne car dans le controller j'ai utilisé $this->view->personne -->
            <tr>
                <td><?php echo $this->escape($client->numeroAdherent); ?></td>
                <td><?php echo $this->escape($client->nom); ?></td>
        		<td><?php echo $this->escape($client->prenom); ?></td>
                <td>
                    <a href="<?php echo $this->url(array('controller'=>'personne',
                        'action'=>'modifier', 'id'=>$client->id));?>">Modifier</a>
                    &nbsp|&nbsp
                    <a href="<?php echo $this->url(array('controller'=>'personne',
                       'action'=>'detail', 'id'=>$client->id));?>">Détails</a>
                </td>

            </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>
<?php echo $this->paginator; ?>
