<?php
$this->title = 'Les personnes';
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'personne',
        'action'=>'ajouter'));?>">Ajouter des personnes</a></p>
<table>
    <tr>
        <th>Nom</th>
        <th>Prénom</th>
				<th>Courriel</th>
				<th></th>
    </tr>
<?php foreach($this->personne as $personne) : ?>
    <tr>
        <td><?php echo $this->escape($personne->nom); ?></td>
		<td><?php echo $this->escape($personne->prenom); ?></td>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'personne',
                'action'=>'modifier', 'id'=>$personne->id));?>">Modifier</a>
        </td>

    </tr>
<?php endforeach; ?>
</table>
