<?php
$this->title = 'Videoclub ZF';
$this->headTitle($this->title);
?>

<table>
    <tr>
        <th>Bienvenue !!!</th>
    </tr>
    <tr>
        <td>Voici les actions disponibles dans l'application :</td>
    </tr>
    <tr>
        <td><li>Gérer les films</li></td>
    </tr>
    <tr>
        <td><li>Gérer les genres</li></td>
    </tr>
    <tr>
        <td><li>Gérer les personnes (clients et employés)</li></td>
    </tr>
    <tr>
        <td><li>Gérer les acteurs et les réalisateurs des films</li></td>
    </tr>

</table>
