<?php
$this->title = 'Les genres';
$this->headTitle($this->title);
?>
<p>Tous ce qui concerne les genres des films.</p>
<P>Vous pouvez afficher tous les genres.<br />
<a href="<?php echo $this->url(array('controller'=>'genre',
        'action'=>'liste'));?>">Afficher tous les genres</a></p>
<p>Vous pouvez ajouter un nouveau genre.<br />
<a href="<?php echo $this->url(array('controller'=>'genre',
        'action'=>'ajouter'));?>">Ajouter de nouveaux genres</a></p>
<p>Vous pouvez rechercher un genre de film.<br />
<a href="<?php echo $this->url(array('controller'=>'genre',
        'action'=>'rechercher'));?>">Rechercher un genre</a></p>
