<?php
$this->title = 'Videoclub ZF';
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'genre',
        'action'=>'ajouter'));?>">Ajouter de nouveaux genres</a></p>

<div class="row">
    <div class="col-sm-12 col-md-offset-5 col-md-7">
        <table>
            <tr>
                <th>Genres</th>
                <th></th>
            </tr>
        <?php
        foreach($this->paginator as $genre) : ?>
            <tr>
                <td><?php echo $this->escape($genre->genre);?></td>

                <td>
                    <a href="<?php echo $this->url(array('controller'=>'genre',
                        'action'=>'modifier', 'id'=>$genre->id));?>">Modifier</a>

                </td>

            </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>
<?php echo $this->paginator; ?>
