<?php
$this->title = 'Tous les genres';
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'genre',
        'action'=>'ajouter'));?>">Ajouter de nouveaux genres</a></p>
<table>
    <tr>
        <th>Genre</th>
        <th></th>
    </tr>
<?php
foreach($this->entries as $genre) : ?>
    <tr>
        <td><?php echo $this->escape($genre->genre);?></td>

        <td>
            <a href="<?php echo $this->url(array('controller'=>'genre',
                'action'=>'modifier', 'id'=>$genre->id));?>">Modifier</a>

            <a href="<?php echo $this->url(array('controller'=>'genre',
                'action'=>'supprimer', 'id'=>$genre->id));?>">Supprimer</a>
        </td>

    </tr>
<?php endforeach; ?>
</table>
