<div class="row" id="pagination_list">
    <div class="col-sm-12 col-md-offset-5 col-md-7">

        <?php if ($this->pageCount): ?>

            <!-- First page link -->
            <?php if (isset($this->previous)): ?>
              <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
                Début
              </a> |
            <?php else: ?>
              <span class="disabled">Début</span> |
            <?php endif; ?>

            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
              <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
                &lt; Précédent
              </a> |
            <?php else: ?>
              <span class="disabled">&lt; Précédent</span> |
            <?php endif; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
              <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
                Suivant &gt;
              </a> |
            <?php else: ?>
              <span class="disabled">Suivant &gt;</span> |
            <?php endif; ?>

            <!-- Last page link -->
            <?php if (isset($this->next)): ?>
              <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
                Fin
              </a>
            <?php else: ?>
              <span class="disabled">Fin</span>
            <?php endif; ?>

        <?php endif; ?>

    </div>
</div>
