<?php
$this->title = 'Les Acteurs Réalisateurs';
$this->headTitle($this->title);
?>
<p>Tous ce qui concerne les acteurs et les réalisateurs des films.</p>
<P>Vous pouvez afficher tous les acteurs et réalisateurs.<br />
<a href="<?php echo $this->url(array('controller'=>'acteurRealisateur',
        'action'=>'liste'));?>">Afficher la liste</a></p>
<p>Vous pouvez ajouter un acteur ou un réalisateur.<br />
<a href="<?php echo $this->url(array('controller'=>'acteurRealisateur',
        'action'=>'ajouter'));?>">Ajouter</a></p>
<p>Vous pouvez rechercher un acteur ou un réalisateur.<br />
<a href="<?php echo $this->url(array('controller'=>'acteurRealisateur',
        'action'=>'rechercher'));?>">Rechercher</a></p>
