<?php
$this->title = 'Videoclub ZF';
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'film',
	'action'=>'ajoutermediadvd', 'id'=>$this->film->id));?>">Ajouter un DVD</a>
&nbsp|&nbsp
<a href="<?php echo $this->url(array('controller'=>'film',
	'action'=>'ajoutermediablueray', 'id'=>$this->film->id));?>">Ajouter un Blu-Ray</a></p>
<div class="row">
    <div class="col-sm-12 col-md-offset-4 col-md-8">
        <table>
            <tr>
                <th>Référence du média</th>
                <th>Type de média</th>
        		<th></th>
            </tr>
        <?php foreach($this->paginator as $media) : ?>
            <tr>
                <td><?php echo $this->escape($media->id); ?></td>
                <td><?php echo $this->escape($media->typeMedia); ?></td>
                <td>
                    <a href="<?php echo $this->url(array('controller'=>'film',
                       'action'=>'desactive', 'id'=>$media->id));?>">Désactiver</a>
                </td>

            </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>
<?php echo $this->paginator; ?>
