<?php
$this->title = 'Videoclub ZF';
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'film',
        'action'=>'ajouter'));?>">Ajouter un film</a></p>
<div class="row">
    <div class="col-sm-12 col-md-offset-2 col-md-10">
        <table>
            <tr>
                <th>Nom</th>
                <th>Résumé</th>
        		<th></th>
            </tr>
        <?php
        foreach($this->paginator as $film) : ?> <!-- je met $this->paginator car dans le controller j'ai utilisé $this->view->paginator -->
            <tr>
                <td><?php echo $this->escape($film->nom); ?></td>
        		<td class="resume"><?php echo $this->escape($film->resume); ?></td>

                <td>
                    <a href="<?php echo $this->url(array('controller'=>'film',
                        'action'=>'modifier', 'id'=>$film->id));?>">Modifier</a>
                    &nbsp|&nbsp
                    <a href="<?php echo $this->url(array('controller'=>'film',
                       'action'=>'detail', 'id'=>$film->id));?>">Détails</a>
                </td>

            </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>
<?php echo $this->paginator; ?>
