<?php
$this->headMeta()->setCharset('UTF-8'); // réglage encodage HTML5
$this->headMeta()->appendHttpEquiv('Content-Language', 'fr-FR') // déclaration de la langue du site
                 ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); // comptatible Edge
$this->headMeta()->appendName('keywords', 'videoclub, gestion film, location film') // pour SEO
                 ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                 ->appendName('description', 'projet NFE102, gestion d\'un videoclub') // description du site
                 ->appendName('author', 'Arnaud Charron'); // auteur du site
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Videoclub');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
    <?php echo $this->headMeta() ; ?>
    <?php echo $this->headTitle() ; ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/bootstrap/css/bootstrap.css')
                                ->headLink(array('rel' => 'icon', 'href' => '/img/favicon.ico'), 'PREPEND')
                                ->headLink(array('rel' => 'stylesheet', 'type' => 'text/css', 'href' => 'https://fonts.googleapis.com/css?family=Oswald')) ; ?>
</head>

<body>
    <div class="container-fluid">
        <header class="row" id="page_header">
            <!-- logo du site -->
            <div class="col-sm-4 col-md-offset-2 col-md-3 col-lg-offset-2 col-lg-3" id="logo">
                <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'index')); ?>" style="text-decoration:none">
                    <!-- <img src="<?php echo $this->baseUrl().'/img/logo.jpg' ; ?>" alt="logo" /> -->
                </a>
            </div>
            <!-- nom du site -->
            <div class="col-sm-6 col-md-7 col-lg-7" id="site_name">
                <h1><?php /* echo $this->url(array('controller'=>'index', 'action'=>'index'));*/ echo $this->title; ?></h1>
            </div>

        </header>

        <div class="row" id="bar"></div>

        <div class="container-fluid">

            <nav class="navbar navbar-inverse" id="menu_videoclub">
                <div class="container-fluid">
                  <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->url(array('controller'=>'index' , 'action'=>'index')); ?>"><span class="glyphicon glyphicon-home"></span></a></li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" href="<?php echo $this->url(array('controller'=>'film' , 'action'=>'index')); ?>"><span class="glyphicon glyphicon-film"></span> Les films<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller'=>'film' , 'action'=>'liste')); ?>"><span class="glyphicon glyphicon-list"></span> Voir tous les films</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'film' , 'action'=>'ajouter')); ?>"><span class="glyphicon glyphicon-plus"></span> Ajouter un film</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'genre' , 'action'=>'liste')); ?>"><span class="glyphicon glyphicon-list"></span> Voir les genres</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'genre' , 'action'=>'ajouter')); ?>"><span class="glyphicon glyphicon-plus"></span> Ajouter un genre</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'acteurRealisateur' , 'action'=>'liste')); ?>"><span class="glyphicon glyphicon-list"></span> Voir les acteurs/réalisateurs</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'acteurRealisateur' , 'action'=>'ajouter')); ?>"><span class="glyphicon glyphicon-plus"></span> Ajouter un acteur/réalisateur</a></li>
                        </ul></li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> Les personnes<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <!-- <li><a href="<?php echo $this->url(array('controller'=>'personne' , 'action'=>'liste')); ?>"><span class="glyphicon glyphicon-list"></span> Tout le monde</a></li> -->
                            <li><a href="<?php echo $this->url(array('controller'=>'personne' , 'action'=>'liste-client')); ?>"><span class="glyphicon glyphicon-list"></span> Voir tous les clients</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'personne' , 'action'=>'liste-employe')); ?>"><span class="glyphicon glyphicon-list"></span> Voir tous les employés</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'personne' , 'action'=>'ajouter')); ?>"><span class="glyphicon glyphicon-info-plus"></span> Ajouter un compte</a></li>
                        </ul></li>
                    <li><a href="#"><span class="glyphicon glyphicon-eye-open"></span> Les locations</a></li>
                    <ul class="dropdown-menu">
                      <li><a href="#"><span class="glyphicon glyphicon-info-sign"></span> Ajouter un compte</a></li>
                      <li><a href="#"><span class="glyphicon glyphicon-edit"></span> Modifier un compte</a></li>
                      <li class="divider"></li>
                      <li><a href="#"><span class="glyphicon glyphicon-off"></span> Désactiver une personne</a></li>
                    </ul></li>
                  </ul>
                  <!-- Formulaire pour la zone de recherche
                 <form method="get" action="search.php" class="navbar-form navbar-right inline-form">
                    <div class="form-group">
                      <input type="search" id="search" name="keywords" class="input-sm form-control" placeholder="Recherche">
                      <button type="submit" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-search"></span> Chercher</button>
                    </div>
                  </form> -->
                </div>
            </nav>

          <div class="site_body" id="content">
              <?php echo $this->layout()->content; ?>
          </div>

        </div>
        <!-- pied de page -->
        <div class="container">
            <footer class="row" id="page_footer">
            <div class="col-sm-12 col-md-offset-2 col-md-8">
              <p>Copyright &copy; <?php echo date('Y', time()); ?> Arnaud Charron. Tous droits réservés -
                <a href="<?php echo $this->url(array('controller'=>'index' , 'action'=>'index')); ?>">Me contacter</a>
                -
                <a href="<?php echo $this->url(array('controller'=>'index' , 'action'=>'index')); ?>">Conditions générales d'utilisation</a></p>
            </div>
            </footer>
        </div>

    </div>

    <?php
        echo $this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.js')
                                ->appendFile($this->baseUrl().'/bootstrap/js/bootstrap.js');
    ?>
</body>

</html>
